export const ADD_NOTE = 'ADD_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const ADD_NOTE_SAGA = 'ADD_NOTE_SAGA';
export const EDIT_NOTE_SAGA = 'EDIT_NOTE_SAGA';

export const DELETE_POST_REQUEST = 'DELETE_NOTE_SAGA';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
